let URL_ENVIRONMENT = "http://localhost:8080/";

// eslint-disable-next-line no-unused-vars
const InveServices = {
    LOGIN: URL_ENVIRONMENT + "inve-back/LoginModule/login-web",
    CHECKSESSION: URL_ENVIRONMENT + "inve-back/services/sessiondata",
    GET_DOCINV_SPLIT: URL_ENVIRONMENT + "inve-back/services/DocInvService/getDocInvSplit",
    SAVE_LGTYP_IM: URL_ENVIRONMENT + "inve-back/services/LgTypService/saveLgTypIM",
    DELETE_LGTYPS_IM: URL_ENVIRONMENT + "inve-back/services/LgTypService/deleteLgTypsIM",
    GET_BUKRS: URL_ENVIRONMENT + "inve-back/services/BukrsService/getBukrs",
    GET_BUKRS_AND_WERKS: URL_ENVIRONMENT + "inve-back/services/BukrsService/getBukrsAndWerks",
    GET_NGORTS_IM: URL_ENVIRONMENT + "inve-back/services/LgortService/getNgortsIM",
    GET_LGORT_AND_WERKS: URL_ENVIRONMENT + "inve-back/services/LgortService/getLgortAndWerks",
    GET_LGTYPS_ONLY: URL_ENVIRONMENT + "inve-back/services/LgTypService/getLgTypsOnly",
    GET_LGTYPS_IM: URL_ENVIRONMENT + "inve-back/services/LgTypService/getLgTypsIM",
    ADD_ZONE: URL_ENVIRONMENT + "inve-back/services/ZoneService/addZone",
    DELETE_ZONE: URL_ENVIRONMENT + "inve-back/services/ZoneService/deleteZone",
    GET_MATNR: URL_ENVIRONMENT + "inve-back/services/MatnrService/getMatnr",
    GET_ZONE_ONLY: URL_ENVIRONMENT + "inve-back/services/ZoneService/getZoneOnly",
    GET_ZONES: URL_ENVIRONMENT + "inve-back/services/ZoneService/getZones",
    GET_ZONE: URL_ENVIRONMENT + "inve-back/services/ZoneService/getZone",
    GET_TGORT: URL_ENVIRONMENT + "inve-back/services/TgortService/getTgort",
    GET_LAGP: URL_ENVIRONMENT + "inve-back/services/LgplaService/getLagp",
    ADD_ROUTE: URL_ENVIRONMENT + "inve-back/services/RouteService/addRoute",
    DELETE_ROUTE: URL_ENVIRONMENT + "inve-back/services/RouteService/deleteRoute",
    GET_DOC_BY_ASSIGNED_ROUTE: URL_ENVIRONMENT + "inve-back/services/RouteService/getDocByAssignedRoute",
    GET_CLOSED_CONCILIATIONS_ID: URL_ENVIRONMENT + "inve-back/services/ConciliationSAPService/getClosedConciliationsID",
    GET_REPORTE_DOCINV_SAP_BY_WERKS: URL_ENVIRONMENT + "inve-back/services/ReportesService/getReporteDocInvSAPByWerks",
    GET_ROUTES: URL_ENVIRONMENT + "inve-back/services/RouteService/getRoutes",
    GET_ZONE_INFO_BY_ROUTE_ID: URL_ENVIRONMENT + "inve-back/services/ZoneService/getZoneInfoByRouteId",
    FORCED_CONCLUDE_TASK: URL_ENVIRONMENT + "inve-back/services/TaskService/forcedConcludeTask",
    ADD_GROUP: URL_ENVIRONMENT + "inve-back/services/GroupService/addGroup",
    GET_UME_USERS: URL_ENVIRONMENT + "inve-back/services/GroupService/getUMEUsers",
    GET_ONLY_GROUPS: URL_ENVIRONMENT + "inve-back/services/GroupService/getOnlyGroups",
    ASSIGN_GROUP_TO_USER: URL_ENVIRONMENT + "inve-back/services/GroupService/assignGroupToUser",
    UNASSIGN_GROUP_TO_USER: URL_ENVIRONMENT + "inve-back/services/GroupService/unAssignGroupToUser",
    GET_USERS_GROUP: URL_ENVIRONMENT + "inve-back/services/GroupService/getUsersGroup",
    DELETE_GROUP: URL_ENVIRONMENT + "inve-back/services/GroupService/deleteGroup",
    GET_DOC_BY_ASSINED_GROUP: URL_ENVIRONMENT + "inve-back/services/GroupService/getDocByAssignedGroup",
    GET_ONLY_DOC_INV: URL_ENVIRONMENT + "inve-back/services/DocInvService/getOnlyDocInv",
    GET_DOC_INV: URL_ENVIRONMENT + "inve-back/services/DocInvService/getDocInv",
    DELETE_DOC_INV: URL_ENVIRONMENT + "inve-back/services/DocInvService/deleteDocInv",
    ADD_LIST_DOC_INV: URL_ENVIRONMENT + "inve-back/services/DocInvService/addListDocInv",
    GET_GROUPS: URL_ENVIRONMENT + "inve-back/services/GroupService/getGroups",
    CHANGE_ASSIGNED_TO_IN_TASK: URL_ENVIRONMENT + "inve-back/services/TaskService/changeAssignedToInTask",
    CHANGE_ROUTE_GROUP: URL_ENVIRONMENT + "inve-back/services/RouteService/changeRouteGroup",
    CHANGE_GROUP_TASK: URL_ENVIRONMENT + "inve-back/services/TaskService/changeGroupTask",
    GET_ONLY_ROUTES: URL_ENVIRONMENT + "inve-back/services/RouteService/getOnlyRoutes",
    GET_CLASSIFICATION: URL_ENVIRONMENT + "inve-back/services/SapServices/getClassification",
    GET_SYSTEM_CLASS_INV_CIC: URL_ENVIRONMENT + "inve-back/services/SapServices/getSystemClassInvCic",
    SET_SYSTEM_CLASS_INV_CIC: URL_ENVIRONMENT + "inve-back/services/SapServices/setSystemClassInvCic",
    VALIDATE_MATNR: URL_ENVIRONMENT + "inve-back/services/SapServices/validateMatnr",
    GET_CONCILIATIONS_ID: URL_ENVIRONMENT + "inve-back/services/ConciliationService/getConciliationsID",
    GET_CONCILIATION_ID_CHILDS: URL_ENVIRONMENT + "inve-back/services/ConciliationService/getConciliationIDChilds",
    GET_CONCILIATION: URL_ENVIRONMENT + "inve-back/services/ConciliationService/getConciliation",
    GET_ZONE_POSITION: URL_ENVIRONMENT + "inve-back/services/ConciliationService/getZonePosition",
    ADD_TASK: URL_ENVIRONMENT + "inve-back/services/TaskService/addTask",
    GET_SPECIAL_COUNT: URL_ENVIRONMENT + "inve-back/services/ConciliationService/getSpecialCount",
    GET_FATHER_TASK_BY_DOC_ID: URL_ENVIRONMENT + "inve-back/services/ConciliationService/getFatherTaskByDocId",
    CONCI_DOC_INV: URL_ENVIRONMENT + "inve-back/services/DocInvService/conciDocInv",
    CLOSE_DOCS_SPLIT: URL_ENVIRONMENT + "inve-back/services/DocInvService/closeDocsSplit",
    GET_OPTIONS: URL_ENVIRONMENT + "inve-back/services/Repository/getOptions",
    SAVE_OPTIONS: URL_ENVIRONMENT + "inve-back/services/Repository/saveOption",
    DELETE_OPTIONS: URL_ENVIRONMENT + "inve-back/services/Repository/deleteOptions",
    GET_COMPLETE_COUNTED_REPORT_DIALY: URL_ENVIRONMENT + "inve-back/services/DocInvService/getCompleteCountedReportDialy",
    GET_TMATNR: URL_ENVIRONMENT + "inve-back/services/MatnrService/getTmatnr",
    GET_BUKRS_WERKS_MULTI_ALMACEN: URL_ENVIRONMENT + "inve-back/services/BukrsService/getBukrsWerksMultiAlmacen",
    SAVE_BUKRS_AND_WERKS_MULTI_ALMACEN: URL_ENVIRONMENT + "inve-back/services/BukrsService/saveBukrsAndWerksMultiAlmacen",
    IS_URBAN: URL_ENVIRONMENT + "inve-back/services/BukrsService/isUrban",
    SAVE_BUKRS_AND_WERKS_URBAN: URL_ENVIRONMENT + "inve-back/services/BukrsService/saveBukrsAndWerksUrban",
    GET_BUKRS_WERKS_URBAN: URL_ENVIRONMENT + "inve-back/services/BukrsService/getBukrsWerksUrban",
    IS_MULTI_ALMACEN: URL_ENVIRONMENT + "inve-back/services/BukrsService/isMultiAlmacen",
    ADD_CATEGORY: URL_ENVIRONMENT + "inve-back/services/CatByMatnrService/addCategory",
    GET_CATEGORIES: URL_ENVIRONMENT + "inve-back/services/CategoryCatService/getCategories",
    SAVE_CATEGORY: URL_ENVIRONMENT + "inve-back/services/CategoryCatService/saveCategory",
    DELETE_CATEGORIES: URL_ENVIRONMENT + "inve-back/services/CategoryCatService/deleteCategories",
    GET_MATNR_CAT_ID_MAKTX: URL_ENVIRONMENT + "inve-back/services/CatByMatnrService/getMatnrCatIdMaktx",
    ADD_MATNR: URL_ENVIRONMENT + "inve-back/services/CatByMatnrService/addMatnr",
    DELETE_MATNR: URL_ENVIRONMENT + "inve-back/services/CatByMatnrService/deleteMatnr",
    GET_JUSTIFIES: URL_ENVIRONMENT + "inve-back/services/JustifyCatService/getJustifies",
    ADD_JUSTIFY: URL_ENVIRONMENT + "inve-back/services/JustifyCatService/addJustify",
    DELETE_JUSTIFIES: URL_ENVIRONMENT + "inve-back/services/JustifyCatService/deleteJustifies",
    GET_EXPLOSION_REPORT_BY_WERKS: URL_ENVIRONMENT + "inve-back/services/ExplosionService/getExplosionReportByWerks",
    SAVE_EXPLOSION_REPORT_BY_WERKS: URL_ENVIRONMENT + "inve-back/services/ExplosionService/saveExplosionReportByWerks",
    SET_CLASS_VALUATION: URL_ENVIRONMENT + "inve-back/services/SapServices/setClassValuation",
    GET_CLASS_VALUATION: URL_ENVIRONMENT + "inve-back/services/SapServices/getClassValuation",
    GET_RETORNABLE_VALUATION: URL_ENVIRONMENT + "inve-back/services/RetornablesService/getRetornableValuation",
    SET_RETORNABLE_VALUATION: URL_ENVIRONMENT + "inve-back/services/RetornablesService/setRetornableValuation",
    GET_JS_FILE_BASE_64: URL_ENVIRONMENT + "inve-back/services/JustificationFileService/getjsFileBase64",
    SAVE_CONCILIATION: URL_ENVIRONMENT + "inve-back/services/ConciliationSAPService/saveConciliation",
    UPLOAD_FILE: URL_ENVIRONMENT + "inve-back/services/JustificationFileService/uploadFile",
    GET_SPECIAL_SAP_COUNT: URL_ENVIRONMENT + "inve-back/services/ConciliationSAPService/getSpecialSAPCount",
    GET_REPORTE_DOC_INV_BY_LGPLA: URL_ENVIRONMENT + "inve-back/services/ReportesService/getReporteDocInvByLgpla",
    GET_EXPLOSION_REPORT_BY_LGPLA: URL_ENVIRONMENT + "inve-back/services/ExplosionService/getExplosionReportByLgpla",
    SAVE_EXPLOSION_REPORT_BY_LGPLA: URL_ENVIRONMENT + "inve-back/services/ExplosionService/saveExplosionReportByLgpla",
    GET_SPECIAL_SAP_COUNT_LIST: URL_ENVIRONMENT + "inve-back/services/ConciliationSAPService/getSpecialSAPCountList",
    GET_SPECIAL_SAP_COUNT_LIST_LGPLA: URL_ENVIRONMENT + "inve-back/services/ConciliationSAPService/getSpecialSAPCountListLgpla",
    GET_SPLIT_DOCS_TO_RECOUNT_LGPLA: URL_ENVIRONMENT + "inve-back/services/DocInvService/getSplitDocsToRecountLgpla",
    GET_EXTRACT_TABLES: URL_ENVIRONMENT + "inve-back/services/ConciliationSAPService/getConciliacionDetails",
    GET_RETORNABLES_VALUATION: URL_ENVIRONMENT + "inve-back/services/RetornablesService/getRetornableValuation",
    SET_RETORNABLES_VALUATION: URL_ENVIRONMENT + "inve-back/services/RetornablesService/setRetornableValuation",
    GET_SUMARY_BY_COUNTRY_REGION: URL_ENVIRONMENT + "inve-back/services/DashboardController/getSumaryByCountryRegion",
    GET_PRICES_MATNR: URL_ENVIRONMENT + "inve-back/services/PriceService/getPricesMatnr",
    GET_SUMARY_BY_DRV: URL_ENVIRONMENT + "inve-back/services/DashboardController/getSumaryByDRV",
    ADD_DRV: URL_ENVIRONMENT + "inve-back/services/DashboardController/addDRV",
    UPDATE_DRV: URL_ENVIRONMENT + "inve-back/services/DashboardController/updateDRV",
    GET_DRV_FOR_MANAGEMENT: URL_ENVIRONMENT + "inve-back/services/DashboardController/getDRVsForManagement",
    UPLOAD_DRVS: URL_ENVIRONMENT + "inve-back/services/DashboardController/uploadDRVs",
    GET_ALL_DRVS_IDS: URL_ENVIRONMENT + "inve-back/services/DashboardController/getAllDRVsIDs",
    DELETE_WERKS_IN_DRV: URL_ENVIRONMENT + "inve-back/services/DashboardController/deleteWerksInDRV",
    LOCK_WERKS_IN_DRV: URL_ENVIRONMENT + "inve-back/services/DashboardController/lockWerksInDRV",
    GET_REGIONS_BY_REGIONS_OR_SAP_COUNTRY: URL_ENVIRONMENT + "inve-back/services/SapCountryService/getRegionsByRegionOrSAPCountry",
    DELETE_REGIONS: URL_ENVIRONMENT + "inve-back/services/SapCountryService/deleteRegion",
    GET_COUNTER_TASK: URL_ENVIRONMENT + "inve-back/services/TaskService/getCounterTask",
    GET_SUMARY_BY_WERKS: URL_ENVIRONMENT + "inve-back/services/DashboardController/getSumaryByWerks",
    GET_SUMARY_BY_MATNR: URL_ENVIRONMENT + "inve-back/services/DashboardController/getSumaryByMatnr",
    GET_LGORTS_BY_DOC: URL_ENVIRONMENT + "inve-back/services/LgortService/getLgortsByDoc",
    SAVE_EXPLOSION_DETAIL: URL_ENVIRONMENT + "inve-back/services/ExplosionService/saveExplosionDetail",
    GET_EXPLOSION_DETAIL: URL_ENVIRONMENT + "inve-back/services/ExplosionService/getExplosionDetail",
    GET_DOCS_FOR_DOWNLOAD: URL_ENVIRONMENT + "inve-back/services/DashboardController/getDocsForDownload",
    GET_FRESCURA: URL_ENVIRONMENT + 'inve-back/services/FrescuraService/getFrescura',
    EXTRACT_MCHB: URL_ENVIRONMENT +'inve-back/services/FrescuraService/extractManualFromSAP_MCHB',
    FRESC_GET_CONCILIATIONS_ID: URL_ENVIRONMENT +'inve-back/services/ConciliationFrescuraService/getConciliationsID',
    FRESC_GET_CONCILIATIONS_ID_CHILDS: URL_ENVIRONMENT +'inve-back/services/ConciliationFrescuraService/getConciliationIDChilds',
    FRESC_GET_CONCILIATION: URL_ENVIRONMENT +'inve-back/services/ConciliationFrescuraService/getConciliation',
    FRESC_GET_CLOSED_CONCILIATIONS_ID: URL_ENVIRONMENT +'inve-back/services/ConciliationFrescuraService/getClosedConciliationsID',
    SET_DETAILS_FRESCURA: URL_ENVIRONMENT +'inve-back/services/FrescuraService/setDetailsFrescura',
    DELETE_DETAILS_FRESCURA: URL_ENVIRONMENT +'inve-back/services/FrescuraService/deleteDetailsFrescura',
    GET_CLOSED_CONCILIATIONS_FRESCURA: URL_ENVIRONMENT +'inve-back/services/ConciliationFrescuraService/getClosedConciliationsFrescura',
    EXTRACT_MBEW_FRESCURA: URL_ENVIRONMENT +'inve-back/services/FrescuraService/extractMBEW_Frescura',
    FRESC_GET_SPECIAL_COUNT: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/getSpecialCount",
    GET_SQL_MCHB: URL_ENVIRONMENT + "inve-back/services/FrescuraService/getSQL_MCHB",
    GET_SAVED_CONCILIATIONS_FRESCURA: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/getSavedConciliationsFrescura",
    GET_SKU_CANALES: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/getSkuCanales",
    GET_REGLAS_FRESCURA: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/getReglasFrescura",
    SAVE_SKU_CANAL: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/saveSkuCanal",
    DELETE_SKU_CANAL: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/deleteSkuCanal",
    SAVE_REGLAS_FRESCURA: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/saveReglasFrescura",
    DELETE_REGLAS_FRESCURA: URL_ENVIRONMENT + "inve-back/services/ConciliationFrescuraService/deleteReglasFrescura",
    GET_ROUTES_BY_USER: URL_ENVIRONMENT + "inve-back/services/RouteService/getRoutesByUser",
    ADD_CONTINGENCY_TASK_COUNT: URL_ENVIRONMENT + "inve-back/services/CountsService/addContingencyTaskCount",
    GET_DOC_BY_TASK_ID: URL_ENVIRONMENT + "inve-back/services/TaskService/getDocByTaskId",
};
const InveTemplates ={
    CAT_BY_MAT : "./resources/templates/template_cat_by_mat.csv",
    JUSTIFICATIONS : "./resources/templates/template_justifications.csv",
    JUSTIFICATIONS_LGPLA : "./resources/templates/template_justificationsLgpla.csv",
    TEMPLATE_DRV : "./resources/templates/template_DRV.csv",
    RETORNABLES : "./resources/templates/template_retornables.csv",
    ROUTES : "./resources/templates/template_routes.csv",
    LGTYP : "./resources/templates/template_lgtyp.csv",
    ZONE : "./resources/templates/template_zone.csv",
    ARMADOS : "./resources/templates/template_armados.csv",
    ARMADOS_COMPLETO : "./resources/templates/template_armadosCompleto.csv"
} 